version: "3.9"

services:
  redis:
    image: redis:8
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data          # persist data khi restart
    command: >
      redis-server
      --save 60 1
      --loglevel warning
    restart: unless-stopped
  postgres:
    image: postgres:16
    container_name: postgres-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mini_ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  redis-data:
  postgres-data:
